### ISSUE TITLE
When doing 'bower install stacky', the lib folder is missing

### ISSUE THREAD

**Issue by raditp** [PolymerLabs/stacky#6]
When doing 'bower install stacky', the lib folder is missing in the installed directory.
This causes error when running web component tester's test case.

**Comment by tinkerD** [comment]
+1

**Comment by azakus** [comment]
Please make sure your copy of web-component-tester is up to date (v4).

**Comment by clubajax** [comment]
I'm using v4 and I have the same problem

**Comment by clubajax** [comment]
I take it back, v4 fixed the bug.
